#!/bin/sh
echo '# Known devices'
echo ''
echo '<!-- This file is automatically generated by makelist.sh -->'
echo '<!-- Do not edit it manually! -->'
echo ''
(
  for FILE in devicereports/*.txt; do
    DEVICENAME=$(head -n1 "$FILE")
    USB=$(echo "$FILE" | cut -d_ -f3 | cut -d. -f1)
    echo "- [$DEVICENAME]($FILE) ($USB)"
  done
) | sort
